### PR TITLE
Transfer old data

### LINKED ISSUE #17: Migrate Member Info
Migrate member info from previous semesters to the atlas DB.
[Previous Semester](https://docs.google.com/spreadsheets/u/1/d/1gznjf7LUG0nA45XprY_mE_z3fTsVx16cgWXl881CO5w/edit#gid=0)

### PR DESCRIPTION
**Pull request by mattwalo32**
## Summary

Created tool to transfer old data to the DB. To run, download data as a CSV file and run ```node db_population_tool.js```

Closes #17

### CODE REVIEW

**Comment by mattwalo32** [comment]
Notice that I pulled from @Qrtn 's dotenv PR so the diff will look a bit strange until that gets merged with main

**Comment by alicesf2** [comment]
Did you run yarn to get the husky commit hook?

**Comment by mattwalo32** [comment]
@alicesf2 Oops forgot that, thanks

**Review by Qrtn — APPROVED** [review]
Nice job, looks great!

**Review by alicesf2 — APPROVED** [review]
amazing 🤩

**Pull request merged**
